image:
  file: .gitpod.Dockerfile

tasks:
  - name: Start Services
    init: |
      docker-compose pull --quiet
    command: |
      docker-compose up -d db
  - name: Other Commands
    init: echo 'init script' # runs during prebuild
    command: echo 'start script'

vscode:
  extensions:
    - GitHub.vscode-pull-request-github
    - ms-azuretools.vscode-docker
    - ms-python.python
    - njpwerner.autodocstring
    - KevinRose.vsc-python-indent
    - formulahendry.code-runner
